**<div style='text-align: center; font-size: 48px'><u>Experiment 5 : Data Analytics II</u></div>**

### <div align="center"> Name : Shravan Santosh Shidruk , PRN : 72311412K </div>

### <div align="center"> Dataset Used : [Social Network Ads Dataset](https://www.kaggle.com/datasets/d4rklucif3r/social-network-ads) </div>

---

### <div align="center"> Dataset Description </div>

This experiment uses the Social Network Ads dataset obtained from Kaggle.

The dataset contains information about users such as age, estimated salary, and whether they purchased a product or not. It is commonly used for classification problems to predict user behavior based on given features.

Source: https://www.kaggle.com/datasets/d4rklucif3r/social-network-ads  

This dataset is suitable for data analytics as it contains features that can be used to build a Logistic Regression model for classification and evaluate performance using a confusion matrix.

---

<b> Variable Descriptions: </b>
 
* Age : Age of the user (Numeric)  
* EstimatedSalary : Estimated salary of the user (Numeric)  
* Purchased : Whether the user purchased the product (Target Variable - Binary Classification)  

---

In [69]:
import pandas as pd
import numpy as np

In [70]:
df = pd.read_csv('Social_Network_Ads.csv')

### Data Preprocessing

In [71]:
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [72]:
df.shape

(400, 3)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB

In [74]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [75]:
df.duplicated().sum()

np.int64(33)

In [76]:
df.drop_duplicates(inplace=True)

In [77]:
df.duplicated().sum()

np.int64(0)

In [78]:
df.shape

(367, 3)

### Dividing Dataset into Independent and Dependent Features

In [79]:
X = df.drop('Purchased',axis=1)
y = df['Purchased']

### Train Test Split

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [81]:
X_train

     Age  EstimatedSalary
162   37            33000
280   59            88000
137   30           107000
234   38           112000
146   27            96000
..   ...              ...
73    33           113000
111   37            71000
288   41            79000
377   42            53000
107   27            89000

[275 rows x 2 columns]

In [82]:
X_test

     Age  EstimatedSalary
204   58           101000
34    27            90000
15    29            80000
334   57            60000
59    32           117000
..   ...              ...
276   38            71000
324   48           131000
115   40            57000
293   37            77000
62    23            66000

[92 rows x 2 columns]

In [83]:
y_train

162    0
280    1
137    1
234    0
146    1
      ..
73     0
111    0
288    0
377    0
107    0
Name: Purchased, Length: 275, dtype: int64

In [84]:
y_test

204    1
34     0
15     0
334    1
59     0
      ..
276    0
324    1
115    0
293    0
62     0
Name: Purchased, Length: 92, dtype: int64

#### Feature Scaling

In [85]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

### Training Logistic Regression Model

In [86]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

### Performance Matrix Evaluation

In [87]:
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

# Extract values
TN, FP, FN, TP = cm.ravel()

print("\nValues from Confusion Matrix:")
print(f"True Negative (TN): {TN}")
print(f"False Positive (FP): {FP}")
print(f"False Negative (FN): {FN}")
print(f"True Positive (TP): {TP}")

# Performance Metrics

# Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)

# Error Rate
error_rate = 1 - accuracy

# Precision (handle division safely)
precision = TP / (TP + FP) if (TP + FP) != 0 else 0

# Recall
recall = TP / (TP + FN) if (TP + FN) != 0 else 0

print("\nPerformance Metrics:")
print(f"Accuracy      : {accuracy:.4f}")
print(f"Error Rate    : {error_rate:.4f}")
print(f"Precision     : {precision:.4f}")
print(f"Recall        : {recall:.4f}")

Confusion Matrix:
[[51  5]
 [ 7 29]]

Values from Confusion Matrix:
True Negative (TN): 51
False Positive (FP): 5
False Negative (FN): 7
True Positive (TP): 29

Performance Metrics:
Accuracy      : 0.8696
Error Rate    : 0.1304
Precision     : 0.8529
Recall        : 0.8056

---

### <div align="center"> Conclusion </div>

- In this experiment, a Logistic Regression model was implemented to perform classification on the Social Network Ads dataset. The model was trained using features such as age and estimated salary to predict whether a user would purchase a product or not.

- The performance of the model was evaluated using a Confusion Matrix, which provided values of True Positive (TP), False Positive (FP), True Negative (TN), and False Negative (FN). Based on these values, various evaluation metrics such as Accuracy, Error Rate, Precision, and Recall were calculated.

- The model achieved an accuracy of approximately 87%, indicating strong overall performance. The precision and recall values also demonstrate a good balance between correctly predicting positive cases and identifying actual positive instances.

- Overall, the Logistic Regression model provides effective classification performance for the given dataset. The use of confusion matrix and evaluation metrics helps in understanding the model's strengths and limitations in detail.

---