**<div style='text-align: center; font-size: 48px'><u>Experiment 6 : Data Analytics III</u></div>**

### <div align="center"> Name : Shravan Santosh Shidruk , PRN : 72311412K </div>

### <div align="center"> Dataset Used : [Iris Dataset](https://www.kaggle.com/datasets/uciml/iris) </div>

---

### <div align="center"> Dataset Description </div>

This experiment uses the Iris dataset obtained from Kaggle.

The dataset contains measurements of iris flowers such as sepal length, sepal width, petal length, and petal width for different species. It is widely used for classification problems to predict the species of a flower based on given features.

Source: https://www.kaggle.com/datasets/uciml/iris  

This dataset is suitable for data analytics as it contains numerical features that can be used to implement a Naïve Bayes classification model and evaluate performance using a confusion matrix.

---

<b> Variable Descriptions: </b>

* sepal_length : Length of the sepal (Numeric)  
* sepal_width : Width of the sepal (Numeric)  
* petal_length : Length of the petal (Numeric)  
* petal_width : Width of the petal (Numeric)  
* species : Type of iris flower (Target Variable - Multi-class Classification)  

---

In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv('iris_data.csv')

### Data Preprocessing

In [20]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [21]:
df.shape

(150, 6)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [23]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

### Dividing Dataset into Independent and Dependent Features

In [25]:
X = df.drop('Species',axis=1)
y = df['Species']

### Train-Test Split

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [27]:
X_train

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
81    82            5.5           2.4            3.7           1.0
133  134            6.3           2.8            5.1           1.5
137  138            6.4           3.1            5.5           1.8
75    76            6.6           3.0            4.4           1.4
109  110            7.2           3.6            6.1           2.5
..   ...            ...           ...            ...           ...
71    72            6.1           2.8            4.0           1.3
106  107            4.9           2.5            4.5           1.7
14    15            5.8           4.0            1.2           0.2
92    93            5.8           2.6            4.0           1.2
102  103            7.1           3.0            5.9           2.1

[105 rows x 5 columns]

In [28]:
X_test

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
73    74            6.1           2.8            4.7           1.2
18    19            5.7           3.8            1.7           0.3
118  119            7.7           2.6            6.9           2.3
78    79            6.0           2.9            4.5           1.5
76    77            6.8           2.8            4.8           1.4
31    32            5.4           3.4            1.5           0.4
64    65            5.6           2.9            3.6           1.3
141  142            6.9           3.1            5.1           2.3
68    69            6.2           2.2            4.5           1.5
82    83            5.8           2.7            3.9           1.2
110  111            6.5           3.2            5.1           2.0
12    13            4.8           3.0            1.4           0.1
36    37            5.5           3.5            1.3           0.2
9     10            4.9           3.1            1.5           0.1
19    20            5.1           3.8            1.5           0.3
56    57            6.3           3.3            4.7           1.6
104  105            6.5           3.0            5.8           2.2
69    70            5.6           2.5            3.9           1.1
55    56            5.7           2.8            4.5           1.3
132  133            6.4           2.8            5.6           2.2
29    30            4.7           3.2            1.6           0.2
127  128            6.1           3.0            4.9           1.8
26    27            5.0           3.4            1.6           0.4
128  129            6.4           2.8            5.6           2.1
131  132            7.9           3.8            6.4           2.0
145  146            6.7           3.0            5.2           2.3
108  109            6.7           2.5            5.8           1.8
143  144            6.8           3.2            5.9           2.3
45    46            4.8           3.0            1.4           0.3
30    31            4.8           3.1            1.6           0.2
22    23            4.6           3.6            1.0           0.2
15    16            5.7           4.4            1.5           0.4
65    66            6.7           3.1            4.4           1.4
11    12            4.8           3.4            1.6           0.2
42    43            4.4           3.2            1.3           0.2
146  147            6.3           2.5            5.0           1.9
51    52            6.4           3.2            4.5           1.5
27    28            5.2           3.5            1.5           0.2
4      5            5.0           3.6            1.4           0.2
32    33            5.2           4.1            1.5           0.1
142  143            5.8           2.7            5.1           1.9
85    86            6.0           3.4            4.5           1.6
86    87            6.7           3.1            4.7           1.5
16    17            5.4           3.9            1.3           0.4
10    11            5.4           3.7            1.5           0.2

In [29]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [30]:
model.fit(X_train,y_train)

GaussianNB()

In [31]:
y_pred = model.predict(X_test)

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
import numpy as np

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

print("\nClass-wise TP, FP, FN, TN:")

total = np.sum(cm)

for i in range(len(cm)):
    TP = cm[i, i]
    FP = np.sum(cm[:, i]) - TP
    FN = np.sum(cm[i, :]) - TP
    TN = total - (TP + FP + FN)

    print(f"\nClass {i}:")
    print(f"TP: {TP}")
    print(f"FP: {FP}")
    print(f"FN: {FN}")
    print(f"TN: {TN}")

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Class-wise TP, FP, FN, TN:

Class 0:
TP: 19
FP: 0
FN: 0
TN: 26

Class 1:
TP: 13
FP: 0
FN: 0
TN: 32

Class 2:
TP: 13
FP: 0
FN: 0
TN: 32

### Performance Metrics

In [33]:
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')

print("\nPerformance Metrics:")
print(f"Accuracy   : {accuracy:.4f}")
print(f"Error Rate : {error_rate:.4f}")
print(f"Precision  : {precision:.4f}")
print(f"Recall     : {recall:.4f}")

# =========================
# Cross Validation
# =========================
model = GaussianNB()
scores = cross_val_score(model, X, y, cv=5)

print("\nCross Validation:")
print(f"Accuracy for each fold: {scores}")
print(f"Average Accuracy     : {scores.mean():.4f}")

Performance Metrics:
Accuracy   : 1.0000
Error Rate : 0.0000
Precision  : 1.0000
Recall     : 1.0000

Cross Validation:
Accuracy for each fold: [0.96666667 1.         1.         1.         1.        ]
Average Accuracy     : 0.9933

---

### <div align="center"> Conclusion </div>

- In this experiment, the Naïve Bayes classification algorithm was implemented on the Iris dataset to classify different species of iris flowers based on their features. The model was trained using numerical attributes such as sepal length, sepal width, petal length, and petal width.

- The performance of the model was evaluated using a Confusion Matrix, which provided values of True Positive (TP), False Positive (FP), True Negative (TN), and False Negative (FN) for each class. Based on these values, performance metrics such as Accuracy, Error Rate, Precision, and Recall were calculated.

- The model achieved an accuracy of 100% on the test data, indicating excellent classification performance. Additionally, cross-validation results showed an average accuracy of approximately 99%, confirming the model’s consistency and reliability across different data splits.

- Overall, the Naïve Bayes algorithm performs very effectively on the Iris dataset due to its well-structured and separable nature. The experiment demonstrates the usefulness of probabilistic classifiers and evaluation metrics in multi-class classification problems.

---